specification:
  - name: "现场位置图"
    local: "local"
    title_font_family: "黑体"
    title_font_color: "#000000"
    title_font_size: 30
    title_is_bold: true
    title_is_italic: false
    title_orientation: "Horizontal"
    title_letter_spacing: 1.5
    title_from_main_bottom_margin: 10
    main_height: 297
    main_width: 420
    main_dpi: 300
    main_border_size: 1
    main_border_color: "#000000"
    main_double_frame: false
    main_left_margin: 22
    main_top_margin: 30
    main_right_margin: 18
    main_bottom_margin: 22
    main_double_frame_fill_color: "#ffffff"
    legend_title: "图例"
    legend_title_font_family: "黑体"
    legend_title_font_color: "#000000"
    legend_title_font_size: 9
    legend_title_letter_spacing: 0.0
    legend_title_spacing_below: 3.5
    legend_spacing_groups_above: 3.00
    legend_spacing_groups_indent: 0.00
    legend_frame_color: "#000000"
    legend_group_headings_font_family: "SimSun"
    legend_group_headings_font_size: 14
    legend_group_headings_font_color: "#000000"
    legend_group_headings_letter_spacing: 0.0
    legend_group_headings_spacing_below_heading: 0.00
    legend_group_headings_spacing_sideof_heading: 0.0
    legend_subgroup_headings_font_family: "SimSun"
    legend_subgroup_headings_font_size: 12
    legend_subgroup_headings_font_color: "#000000"
    legend_subgroup_headings_letter_spacing: 0.0
    legend_subgroup_spacing_above: 3.00
    legend_subgroup_spacing_indent: 0.00
    legend_subgroup_heading_below: 0.00
    legend_subgroup_heading_sideof_heading: 0.00
    legend_items_font_family: "SimSun"
    legend_items_font_size: 12
    legend_items_font_color: "#000000"
    legend_items_letter_spacing: 0.0
    legend_items_space_before_sideof_symbol: 0.00
    legend_items_between_symbol: 2.50
    legend_items_label_space: 2.00
    legend_general_box_space: 2.00
    legend_general_column_space: 2.00
    legend_content_font_family: "SimSun"
    legend_content_font_color: "#000000"
    legend_content_font_size: 6
    left_seam_seal_family: "黑体"
    left_seam_seal_font_color: "#000000"
    left_seam_seal_font_size: 14
    left_seam_seal_from_topborder_top_margin: 5
    left_seam_seal_from_leftborder_right_margin: 5
    left_seam_seal_horizontal_alignment: "center"
    left_seam_seal_vertical_alignment: "center"
    left_seam_seal_text_orientation: "Vertical"
    left_seam_seal_letter_spacing: 3.0
    right_seam_seal_family: "黑体"
    right_seam_seal_font_color: "#000000"
    right_seam_seal_font_size: 14
    right_seam_seal_from_topborder_top_margin: 5
    right_seam_seal_from_rightborder_left_margin: 5
    right_seam_seal_horizontal_alignment: "center"
    right_seam_seal_vertical_alignment: "center"
    right_seam_seal_text_orientation: "Vertical"
    right_seam_seal_letter_spacing: 3.0
    signature_family: "黑体"
    signature_font_color: "#000000"
    signature_font_size: 12
    signature_letter_spacing: 3.0
    signature_from_bottomborder_top_margin: 5
    signature_from_rightborder_right_margin: 5
    commander_family: "黑体"
    commander_font_color: "#000000"
    commander_font_size: 8
    remark_font_family: "SimSun"
    remark_font_color: "#000000"
    remark_font_size: 12
    remark_is_bold: false
    remark_is_italic: false
    remark_bg_color: "#ffffff"
    remark_bg_frame_color: "#000000"
    remark_orientation: "Horizontal"
    remark_letter_spacing: 1.5
    north_base64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAABECAMAAADa37fNAAAA81BMVEUAAAAsLCwFAQEmGhkEAQEFAQEFAQEjGhYkGxsEAQEEAQEkGhYXEhIFAgIIBAQSDw4jIBsFAQEjGRYFAQEGAwMIBAQPDAwJCQkGAQEGAQERDwwGAQEFAgIFAgIGAgIGAgIMCAcFAQEFAQEGAgIHAgIHAwMMCgocFhMFAQEFAQEFAQEFAQEGAQEFAQEGAgIGAgIHAgIHAgIGAgIVFRUFAQEFAQEGAQEGAgIFAwMFAwMGAwMGAwMHBAQjGRYjGRcFAgIkGRcHAgImGhcFAQEjGRYkGhckGhckGRckGRckGRcjGRcjGhcjGhgkGhoGBgYFAQEjGRZXOu2gAAAAT3RSTlMABfs76vbw2Rzt6H8RlToWCdzuy1FDJBrnuB/lpaGcfjXIxIVyTC0o4dXTz66piYFua2cNwbyxeWFeWVVH/J6NhXVY161sZNXJv7WRdEYpLZbk2gAAAtZJREFUSMfNlGl3ojAUhi8ppEIBRREV932tVavVVrsvs0/6/3/NEEIIOLbDOTNnTp8PPSU+JDfvTYA9Uq9HAMcn+8N/raWkJNqP7M0byk3Wg2nS3fXX9Bva0cPDw7OvPX3KviSo7fqbDgm0u38cyPsc3Qjt+/lhxzk5vv4Sahn63wEy2eydKxZ1XvtwkJ4U1Pb5yU2lTrLSH7bw/Ep5bx+ZF9ojvd/v6/ABIdUkVho3k2g2lpNsskqwnUAbkATF9TaYEDXfe0eRdkZxaCFClNywbOzeaOnlYHnvwIoQgtbQv18OLg9I+WHLpD3ViIcfidka5fetTrnLbJlqMruj3XInbhlKAXymiGp4y54K49imK80MMEbEp8LPVW4irHWOWwWZaWWJe+V12B4r7M4VZprW4CO6ZQdxWXmxOmGguojAYjPPSiLgMgnIQUhpRv+eyw5wGhrX5IK4vjK911sxGdwjruGryHRbWs5CDLRIyKkYXVQAJMwSZ+sLrShFzrMEvTGEdFWhaaYYH/dgt4q0jAjQWaS4HWwiXbNIhMgq1Q3UxVsOj2M/krM6zA3gbJSohi9FMXOwL4BzQWJMxA82NMK2SEWhxCPJNUDH/MnU4pps8vfVNMCyC4w6imuozeNc0gNS41Pzn61gKyNg1GZ+DBJrCe/UoNBCbFWXrak5vswmt9WwJJcdO4VF0mbLFVTXt4O4OqK5flauGuR86x+aAZuBpWX45fnlnE75hlcGwE8Wx1APLh6i6+e9OVZhfDpZw0LxI+Wfoj7NGk2hQ29d6MntErVUcbSvaHmPpyQd++C2FFqYAYKqQr9gOsTIe4OomQHB+dAbWUCcNqJ32BUD7qzovVna08ZeYZ2aNmrPbdO052cjrWYuVKIF84tPDKbH2Kwbk2ZzYtRNoJEpNJIIW4xKEuyjP6Lb2ECFWGn4nYZqxZ6LagMO0VGc6Ft4DodpTUEwrcD/5BfGeJjAKlqg2AAAAABJRU5ErkJggg=="
    north_rotate: 0.0
    north_width: 20
    north_height: 20
  - name: "警力部署图"
    local: "deploy"
    title_font_family: "SimSun"
    title_font_color: "#000000"
    title_font_size: 30
    title_is_bold: true
    title_is_italic: false
    title_orientation: "Horizontal"
    title_letter_spacing: 1.5
    title_from_main_bottom_margin: 10
    main_height: 297
    main_width: 420
    main_dpi: 300
    main_border_size: 1
    main_border_color: "#000000"
    main_double_frame: false
    main_left_margin: 22
    main_top_margin: 30
    main_right_margin: 18
    main_bottom_margin: 22
    main_double_frame_fill_color: "#ffffff"
    legend_title: "图例"
    legend_title_font_family: "黑体"
    legend_title_font_color: "#000000"
    legend_title_font_size: 9
    legend_title_letter_spacing: 0.0
    legend_title_spacing_below: 3.5
    legend_spacing_groups_above: 3.00
    legend_spacing_groups_indent: 0.00
    legend_frame_color: "#000000"
    legend_group_headings_font_family: "SimSun"
    legend_group_headings_font_size: 14
    legend_group_headings_font_color: "#000000"
    legend_group_headings_letter_spacing: 0.0
    legend_group_headings_spacing_below_heading: 0.00
    legend_group_headings_spacing_sideof_heading: 0.0
    legend_subgroup_headings_font_family: "SimSun"
    legend_subgroup_headings_font_size: 12
    legend_subgroup_headings_font_color: "#000000"
    legend_subgroup_headings_letter_spacing: 0.0
    legend_subgroup_spacing_above: 3.00
    legend_subgroup_spacing_indent: 0.00
    legend_subgroup_heading_below: 0.00
    legend_subgroup_heading_sideof_heading: 0.00
    legend_items_font_family: "SimSun"
    legend_items_font_size: 12
    legend_items_font_color: "#000000"
    legend_items_letter_spacing: 0.0
    legend_items_space_before_sideof_symbol: 0.00
    legend_items_between_symbol: 2.50
    legend_items_label_space: 2.00
    legend_general_box_space: 2.00
    legend_general_column_space: 2.00
    legend_content_font_family: "SimSun"
    legend_content_font_color: "#000000"
    legend_content_font_size: 6
    left_seam_seal_family: "黑体"
    left_seam_seal_font_color: "#000000"
    left_seam_seal_font_size: 14
    left_seam_seal_from_topborder_top_margin: 5
    left_seam_seal_from_leftborder_right_margin: 5
    left_seam_seal_horizontal_alignment: "center"
    left_seam_seal_vertical_alignment: "center"
    left_seam_seal_text_orientation: "Vertical"
    left_seam_seal_letter_spacing: 3.0
    right_seam_seal_family: "黑体"
    right_seam_seal_font_color: "#000000"
    right_seam_seal_font_size: 14
    right_seam_seal_from_topborder_top_margin: 5
    right_seam_seal_from_rightborder_left_margin: 5
    right_seam_seal_horizontal_alignment: "center"
    right_seam_seal_vertical_alignment: "center"
    right_seam_seal_text_orientation: "Vertical"
    right_seam_seal_letter_spacing: 3.0
    signature_family: "黑体"
    signature_font_color: "#000000"
    signature_font_size: 12
    signature_letter_spacing: 3.0
    signature_from_bottomborder_top_margin: 5
    signature_from_rightborder_right_margin: 5
    commander_family: "黑体"
    commander_font_color: "#000000"
    commander_font_size: 8
    remark_font_family: "SimSun"
    remark_font_color: "#000000"
    remark_font_size: 6
    remark_is_bold: false
    remark_is_italic: false
    remark_bg_color: "#ffffff"
    remark_bg_frame_color: "#000000"
    remark_orientation: "Horizontal"
    remark_letter_spacing: 1.5
    north_base64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAABECAMAAADa37fNAAAA81BMVEUAAAAsLCwFAQEmGhkEAQEFAQEFAQEjGhYkGxsEAQEEAQEkGhYXEhIFAgIIBAQSDw4jIBsFAQEjGRYFAQEGAwMIBAQPDAwJCQkGAQEGAQERDwwGAQEFAgIFAgIGAgIGAgIMCAcFAQEFAQEGAgIHAgIHAwMMCgocFhMFAQEFAQEFAQEFAQEGAQEFAQEGAgIGAgIHAgIHAgIGAgIVFRUFAQEFAQEGAQEGAgIFAwMFAwMGAwMGAwMHBAQjGRYjGRcFAgIkGRcHAgImGhcFAQEjGRYkGhckGhckGRckGRckGRcjGRcjGhcjGhgkGhoGBgYFAQEjGRZXOu2gAAAAT3RSTlMABfs76vbw2Rzt6H8RlToWCdzuy1FDJBrnuB/lpaGcfjXIxIVyTC0o4dXTz66piYFua2cNwbyxeWFeWVVH/J6NhXVY161sZNXJv7WRdEYpLZbk2gAAAtZJREFUSMfNlGl3ojAUhi8ppEIBRREV932tVavVVrsvs0/6/3/NEEIIOLbDOTNnTp8PPSU+JDfvTYA9Uq9HAMcn+8N/raWkJNqP7M0byk3Wg2nS3fXX9Bva0cPDw7OvPX3KviSo7fqbDgm0u38cyPsc3Qjt+/lhxzk5vv4Sahn63wEy2eydKxZ1XvtwkJ4U1Pb5yU2lTrLSH7bw/Ep5bx+ZF9ojvd/v6/ABIdUkVho3k2g2lpNsskqwnUAbkATF9TaYEDXfe0eRdkZxaCFClNywbOzeaOnlYHnvwIoQgtbQv18OLg9I+WHLpD3ViIcfidka5fetTrnLbJlqMruj3XInbhlKAXymiGp4y54K49imK80MMEbEp8LPVW4irHWOWwWZaWWJe+V12B4r7M4VZprW4CO6ZQdxWXmxOmGguojAYjPPSiLgMgnIQUhpRv+eyw5wGhrX5IK4vjK911sxGdwjruGryHRbWs5CDLRIyKkYXVQAJMwSZ+sLrShFzrMEvTGEdFWhaaYYH/dgt4q0jAjQWaS4HWwiXbNIhMgq1Q3UxVsOj2M/krM6zA3gbJSohi9FMXOwL4BzQWJMxA82NMK2SEWhxCPJNUDH/MnU4pps8vfVNMCyC4w6imuozeNc0gNS41Pzn61gKyNg1GZ+DBJrCe/UoNBCbFWXrak5vswmt9WwJJcdO4VF0mbLFVTXt4O4OqK5flauGuR86x+aAZuBpWX45fnlnE75hlcGwE8Wx1APLh6i6+e9OVZhfDpZw0LxI+Wfoj7NGk2hQ29d6MntErVUcbSvaHmPpyQd++C2FFqYAYKqQr9gOsTIe4OomQHB+dAbWUCcNqJ32BUD7qzovVna08ZeYZ2aNmrPbdO052cjrWYuVKIF84tPDKbH2Kwbk2ZzYtRNoJEpNJIIW4xKEuyjP6Lb2ECFWGn4nYZqxZ6LagMO0VGc6Ft4DodpTUEwrcD/5BfGeJjAKlqg2AAAAABJRU5ErkJggg=="
    north_rotate: 0.0
    north_width: 20
    north_height: 20
  - name: "紧急疏散图"
    local: "evacuation"
    title_font_family: "SimSun"
    title_font_color: "#000000"
    title_font_size: 30
    title_is_bold: True
    title_is_italic: False
    title_orientation: "Horizontal"
    title_letter_spacing: 1.5
    title_from_main_bottom_margin: 10
    main_height: 297
    main_width: 420
    main_dpi: 300
    main_border_size: 1
    main_border_color: "#000000"
    main_double_frame: False
    main_left_margin: 22
    main_top_margin: 30
    main_right_margin: 18
    main_bottom_margin: 22
    main_double_frame_fill_color: "#ffffff"
    legend_title: "图例"
    legend_title_font_family: "黑体"
    legend_title_font_color: "#000000"
    legend_title_font_size: 9
    legend_title_letter_spacing: 0.0
    legend_title_spacing_below: 3.5
    legend_spacing_groups_above: 3.00
    legend_spacing_groups_indent: 0.00
    legend_frame_color: "#000000"
    legend_group_headings_font_family: "SimSun"
    legend_group_headings_font_size: 14
    legend_group_headings_font_color: "#000000"
    legend_group_headings_letter_spacing: 0.0
    legend_group_headings_spacing_below_heading: 0.00
    legend_group_headings_spacing_sideof_heading: 0.0
    legend_subgroup_headings_font_family: "SimSun"
    legend_subgroup_headings_font_size: 12
    legend_subgroup_headings_font_color: "#000000"
    legend_subgroup_headings_letter_spacing: 0.0
    legend_subgroup_spacing_above: 3.00
    legend_subgroup_spacing_indent: 0.00
    legend_subgroup_heading_below: 0.00
    legend_subgroup_heading_sideof_heading: 0.00
    legend_items_font_family: "SimSun"
    legend_items_font_size: 12
    legend_items_font_color: "#000000"
    legend_items_letter_spacing: 0.0
    legend_items_space_before_sideof_symbol: 0.00
    legend_items_between_symbol: 2.50
    legend_items_label_space: 2.00
    legend_general_box_space: 2.00
    legend_general_column_space: 2.00
    legend_content_font_family: "SimSun"
    legend_content_font_color: "#000000"
    legend_content_font_size: 6
    left_seam_seal_family: "黑体"
    left_seam_seal_font_color: "#000000"
    left_seam_seal_font_size: 14
    left_seam_seal_from_topborder_top_margin: 5
    left_seam_seal_from_leftborder_right_margin: 5
    left_seam_seal_horizontal_alignment: "center"
    left_seam_seal_vertical_alignment: "center"
    left_seam_seal_text_orientation: "Vertical"
    left_seam_seal_letter_spacing: 3.0
    right_seam_seal_family: "黑体"
    right_seam_seal_font_color: "#000000"
    right_seam_seal_font_size: 14
    right_seam_seal_from_topborder_top_margin: 5
    right_seam_seal_from_rightborder_left_margin: 5
    right_seam_seal_horizontal_alignment: "center"
    right_seam_seal_vertical_alignment: "center"
    right_seam_seal_text_orientation: "Vertical"
    right_seam_seal_letter_spacing: 3.0
    signature_family: "黑体"
    signature_font_color: "#000000"
    signature_font_size: 12
    signature_letter_spacing: 3.0
    signature_from_bottomborder_top_margin: 5
    signature_from_rightborder_right_margin: 5
    commander_family: "黑体"
    commander_font_color: "#000000"
    commander_font_size: 8
    remark_font_family: "SimSun"
    remark_font_color: "#000000"
    remark_font_size: 6
    remark_is_bold: False
    remark_is_italic: False
    remark_bg_color: "#ffffff"
    remark_bg_frame_color: "#000000"
    remark_orientation: "Horizontal"
    remark_letter_spacing: 1.5
    north_base64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAABECAMAAADa37fNAAAA81BMVEUAAAAsLCwFAQEmGhkEAQEFAQEFAQEjGhYkGxsEAQEEAQEkGhYXEhIFAgIIBAQSDw4jIBsFAQEjGRYFAQEGAwMIBAQPDAwJCQkGAQEGAQERDwwGAQEFAgIFAgIGAgIGAgIMCAcFAQEFAQEGAgIHAgIHAwMMCgocFhMFAQEFAQEFAQEFAQEGAQEFAQEGAgIGAgIHAgIHAgIGAgIVFRUFAQEFAQEGAQEGAgIFAwMFAwMGAwMGAwMHBAQjGRYjGRcFAgIkGRcHAgImGhcFAQEjGRYkGhckGhckGRckGRckGRcjGRcjGhcjGhgkGhoGBgYFAQEjGRZXOu2gAAAAT3RSTlMABfs76vbw2Rzt6H8RlToWCdzuy1FDJBrnuB/lpaGcfjXIxIVyTC0o4dXTz66piYFua2cNwbyxeWFeWVVH/J6NhXVY161sZNXJv7WRdEYpLZbk2gAAAtZJREFUSMfNlGl3ojAUhi8ppEIBRREV932tVavVVrsvs0/6/3/NEEIIOLbDOTNnTp8PPSU+JDfvTYA9Uq9HAMcn+8N/raWkJNqP7M0byk3Wg2nS3fXX9Bva0cPDw7OvPX3KviSo7fqbDgm0u38cyPsc3Qjt+/lhxzk5vv4Sahn63wEy2eydKxZ1XvtwkJ4U1Pb5yU2lTrLSH7bw/Ep5bx+ZF9ojvd/v6/ABIdUkVho3k2g2lpNsskqwnUAbkATF9TaYEDXfe0eRdkZxaCFClNywbOzeaOnlYHnvwIoQgtbQv18OLg9I+WHLpD3ViIcfidka5fetTrnLbJlqMruj3XInbhlKAXymiGp4y54K49imK80MMEbEp8LPVW4irHWOWwWZaWWJe+V12B4r7M4VZprW4CO6ZQdxWXmxOmGguojAYjPPSiLgMgnIQUhpRv+eyw5wGhrX5IK4vjK911sxGdwjruGryHRbWs5CDLRIyKkYXVQAJMwSZ+sLrShFzrMEvTGEdFWhaaYYH/dgt4q0jAjQWaS4HWwiXbNIhMgq1Q3UxVsOj2M/krM6zA3gbJSohi9FMXOwL4BzQWJMxA82NMK2SEWhxCPJNUDH/MnU4pps8vfVNMCyC4w6imuozeNc0gNS41Pzn61gKyNg1GZ+DBJrCe/UoNBCbFWXrak5vswmt9WwJJcdO4VF0mbLFVTXt4O4OqK5flauGuR86x+aAZuBpWX45fnlnE75hlcGwE8Wx1APLh6i6+e9OVZhfDpZw0LxI+Wfoj7NGk2hQ29d6MntErVUcbSvaHmPpyQd++C2FFqYAYKqQr9gOsTIe4OomQHB+dAbWUCcNqJ32BUD7qzovVna08ZeYZ2aNmrPbdO052cjrWYuVKIF84tPDKbH2Kwbk2ZzYtRNoJEpNJIIW4xKEuyjP6Lb2ECFWGn4nYZqxZ6LagMO0VGc6Ft4DodpTUEwrcD/5BfGeJjAKlqg2AAAAABJRU5ErkJggg=="
    north_rotate: 0.0
    north_width: 20
    north_height: 20,